### ISSUE TITLE
WEATHERFLOW_COLLECTOR_TOKEN vs WEATHERFLOW_COLLECTIOR_API_TOKEN

### ISSUE THREAD

**Issue by ckuhtz** [lux4rd0/weatherflow-dashboards-aio#10]
Should use same env variable in all places.

Traceback (most recent call last):
  File "/app/weatherflow-collector/./weatherflow-collector.py", line 47, in <module>
    import config
  File "/app/weatherflow-collector/config.py", line 580, in <module>
    "wss://ws.weatherflow.com/swd/data?token=" + WEATHERFLOW_COLLECTOR_API_TOKEN
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by lux4rd0** [comment]
I need to update this AIO since I updated the collector with a brand new one. This won't work as is. I think 3.5.3 may still work? I'll try to fix it asap.

**Comment by ckuhtz** [comment]
Ah, that explains why I was having so many issues. Thank you.

**Comment by jdigangi** [comment]
Is there a fix for this? I tried the AIO and stand alone builds with no joy :-(

**Comment by n3bkv** [comment]
Not sure if this is a related issue but over the last few days the API connection to Tempest has gone down. I checked my API key and even created a new one and tested it with their test endpoint but that does not seem to resolve the issue.  I'm running 3.5.3.
